name: Node.js CI
'on':
  push:
    branches:
      - master
      - alpha
      - beta
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm clean-install
      - run: npm test
      - name: Upload coverage data to Codecov
        run: 'npm run coverage:report'
  release:
    needs: verify
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  release-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - run: npm install --save-dev semantic-release semantic-release-github-pr@6.0.0
      - run: DEBUG=semantic-release:* npx semantic-release-github-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  automerge:
    needs:
      - verify
      - release-preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
